services:
  postgres-admin:
    container_name: con-postgres-admin
    image: bitnami/postgresql:16
    volumes:
      - ./backend/sql/init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: admin
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_PORT: 5432
      TZ: "Europe/Moscow"
    ports:
      - 5544:5432
    networks:
      - mynetwork

  backend-main:
    container_name: con-backend-main
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres-admin:
        condition: service_healthy
    environment:
      POSTGRESQL_HOST: con-postgres-admin
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: postgres
      TZ: "Europe/Moscow"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
