services:
  postgresql-testdb:
    container_name: postgresql-testdb
    image: bitnami/postgresql:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    ports:
      - 7531:5432
    volumes:
      - pgdata:/etc/postgresql/16/main/

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql-testdb
    environment:
      POSTGRES_HOST: postgresql-testdb
      POSTGRES_PORT: 7531
      POSTGRESQL_PORT: 7531
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: testdb
      BACKEND_TYPE: docker
    ports:
      - "9898:9898"
  
volumes:
  pgdata: