services:
  postgresql-testdb:
    container_name: postgresql-testdb
    image: bitnami/postgresql:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    ports:
      - 5544:5432
    volumes:
      - pgdata:/etc/postgresql/16/main/

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql-testdb
    environment:
      POSTGRES_HOST: postgresql-testdb
      POSTGRES_PORT: 5432
      BACKEND_TYPE: docker
    ports:
      - "9898:9898"
  
volumes:
  pgdata: