name: Test JustLabel

on: [push]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: 'Create env file'
        shell: bash
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          STATIC_EMAIL_CODE: ${{ secrets.STATIC_EMAIL_CODE }}
        run: |
          echo "SMTP_HOST=${SMTP_HOST}" >> .env
          echo "USER_EMAIL=${USER_EMAIL}" >> .env
          echo "EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> .env
          echo "STATIC_EMAIL_CODE=${STATIC_EMAIL_CODE}" >> .env

      - name: Run E2E tests
        run: make docker-up -i
      
      - name: Remove env
        run: make docker-down && rm .env
